name: skeleton
description: "Starting point for the Flame and Supabase workshop exercises."
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flame: ^1.38.0
  flutter:
    sdk: flutter
  supabase_flutter: ^3.0.0-dev.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  supabase: ^3.0.0-dev.2
  supabase_typegen: ^0.1.2

flutter:
  uses-material-design: true
