// Generated by supabase_typegen. Do not edit by hand.
//
// Source schema: public

// The typed table access API is still experimental.
// ignore_for_file: experimental_member_use

import 'package:supabase_flutter/supabase_flutter.dart';

/// A row of the `scores` table.
/// One row per pilot with their total round wins
extension type const ScoresRow(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  String get id => _json['id'] as String;
  String get name => _json['name'] as String;
  int get wins => _json['wins'] as int;
  DateTime get updatedAt => DateTime.parse(_json['updated_at'] as String);
}

/// Values for inserting a row into `scores`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const ScoresInsert._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  ScoresInsert({
    required String id,
    required String name,
    int? wins,
    DateTime? updatedAt,
  }) : this._({
         'id': id,
         'name': name,
         'wins': ?wins,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
       });
}

/// Values for updating rows of `scores`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const ScoresUpdate._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  ScoresUpdate({String? id, String? name, int? wins, DateTime? updatedAt})
    : this._({
        'id': ?id,
        'name': ?name,
        'wins': ?wins,
        'updated_at': ?updatedAt?.toUtc().toIso8601String(),
      });
}

/// Typed access to the `scores` table.
class Scores {
  const Scores._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable('scores', ScoresRow.new);

  static const id = TableColumn<String>('id');
  static const name = TableColumn<String>('name');
  static const wins = TableColumn<int>('wins');
  static const updatedAt = TableColumn<DateTime>('updated_at');
}
